[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo 'Client already built'"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/api/:splat"
  status = 200